### ISSUE TITLE
List of Fixes: About and Careers pages

### ISSUE THREAD

**Issue by annabambi** [gravitational/next#257]
@alexwolfe and I would like you to take a look at some small fixes for the Careers and About Up pages.
Please, let us know if you have any questions! thank you!
I will provide you with a new globe skin for a Careers page soon.

**Careers Page:**

Work with Us section: 
- [x] margin-top 8px
- [x] hero has a min height on a desktop 320px
- [x] centered content

Mission section:
- [x] font-size 38px and line-height 48px
- [x] adjust the height of the illustration

We Value section (same for Benefits&Perks):
- [x] font-size 16px and line-height 28px + color #37474F
- [x] margin-left on the headings: 52px
- [x] margin-top on the paragraph below: 16px (see example)
![image (41)](https://user-images.githubusercontent.com/18430731/119055825-8a2aa300-b97e-11eb-8d62-89739c21221f.png)

Our Team all over the Globe section:
- [x] font-size 16px line-height 32px, margin-top 0px
- [x] I will provide you with a new globe skin with some modifications specifically for this page. I also will work on a background for this section.

Work at Teleport:
- [x] font-size 16px line-height 32px, margin-top 0px

Dropdown:
- [x] has to have a grey outline 

**About Us Page:**

Our Story section:
- [x] font-size 16px and line-height 28px + color #37474F

Teleport Manifesto section:
- [x] font-size 16px and line-height 28px
- [x] margin-top 16px p (see example)
![image (42)](https://user-images.githubusercontent.com/18430731/119056731-0ec9f100-b980-11eb-84e9-0ec75f27c073.png)

Our Engineering Principles section:
- [x] font-size 16px and line-height 28px + color #37474F

Careers at Teleport section:
- [x] font-size 16px line-height 32px, margin-top 16px

Trusted by Leading Organizations section:
- [x] font-size 16px line-height 32px + color balck
