### ISSUE TITLE
Improve Lighthouse score by optimisizng third-partd dependencies

### ISSUE THREAD

**Issue by iAdramelk** [gravitational/next#763]
[Lighthouse](https://web.dev/performance-scoring/) is a test created to measure site performance. Google is using Lighthouse score as a part of page ranking algorithm, so having is not only good for end users, but also good for SEO.

I selected one page https://goteleport.com/pricing/ to run some measurements. This page was selected because it has relatively small amount of content and no videos, but it is an important page for conversions and have both Drift and GTM enabled.

Test results for it right now are following:

**Performance:** 48,4 (mean of 5 measurements)
**Accessibility:** 89
**Best practices:** 100
**SEO:** 99

As we can see, most of the params are pretty good, except the **performance** and the main reasons for such low score of performance are: 

1. Amount of requests we have.
2. Amount of code we download.
3. Amount of JS-code we need to parse and execute.

And right now the source of 2/3 requests and 1/2 of the code are a third-party code.

To show what exactly is the source of the code I created different build with different 3rd-partd code parts disables and run some measurements.

## Test description

Service used for testing: https://www.webpagetest.org/lighthouse
Test location: US Virginia
Page for tests: https://goteleport.com/pricing/ (run tests on vercel preview builds)
Hardware: Chrome - Emulated Motorola G (gen 4) - 3GFast
All tests run 5 times and mean value is used

### Baseline: Own code + reCaptcha

Performance score: 60,2 (61, 59, 56, 63, 62)

| Resource Type | Requests | Transfer Size  |
| --------------- | --------: | -------------: |
| Total                  |            65 |     1,018.4 KiB  |
| Image                |            25 |        455.6 KiB |
| Script                |            27 |        368.8 KiB |
| Font                  |              4 |           99.2 KiB |
| Document        |               2 |           41.7 KiB |
| Other                |              5 |           28.5 KiB |
| Stylesheet        |              2 |           24.6 KiB |
| Media               |               0 |            0.0 KiB |
| Third-party      |               7 |        186.0 KiB |

Performance of the baseline is 12 points better then the original. It can of course be better too, but I will add info about it in separate issues.

Third-party here is a reCaptcha (3 JS, 1 Img, 1 CSS, 1 Other), we use it for every form and unfortunately can't fully disable (but probably can defer its initialization until somebody set focus in the form or click submit button).

Our own code here is 832,4 KiB of which only around 24 requests and ~300 KiB of code is JavaScript. It is still more that it should be and we can optimize it further, but there is not that much room for improvement here given the total number of code added by widgets.

### Drift: Baseline + Drift

Performance score: 50,4 (47, 47, 50, 54, 54)

| Resource Type | Requests | Transfer Size |
| --------------- | --------: | -------------: |
| Total                  |         149 |      1,562.1 KiB |
| Script                |           81 |          811.7 KiB |
| Image                |           25 |        455.5 KiB |
| Font                   |             6 |        138.7 KiB |
| Stylesheet         |           14 |          73.6 KiB |
| Document         |             4 |          44.3 KiB |
| Other                 |           19 |          38.3 KiB |
| Media                |             0 |            0.0 KiB |
| Third-party       |            91 |       729.5 KiB |

From this report "Reduce the impact of third-party code" became main advice for optimizations.

Drift added 84 requests and 543,5 KiB to our page, or around the third of it's size. It's a lot and one of the main sources of performance issues. 

I do understand that we can't remove it completely, but we can replace actual widget with placeholder and delay its initialization until the icon is clicked. There is a library just for that: https://github.com/calibreapp/react-live-chat-loader

Adding it will prevent some drift features from working (like automatically opening the bot and starting the chat), but it will make our page size 1/3 smaller. It look like a good compromise to me.

### GTM: Baseline + GTM + GTAG

Performance score: 56,4 (52, 61, 61, 54, 54)

| Resource Type | Requests | Transfer Size |
| --------------- | --------: | -------------: |
| Total                  |            91 |     1,190.4 KiB | 
| Script                |            37 |       533.9 KiB |
| Image                |            30 |       456.5 KiB |
| Font                   |              4 |         99.3 KiB |
| Document         |               2 |         41.4 KiB |
| Other                 |             16 |        34.8 KiB |
| Stylesheet         |               2 |        24.6 KiB |
| Media                 |               0 |          0.0 KiB |
| Third-party        |             33 |      357.8 KiB |

GTM and counters inside it add 26 requests and 171,8 KiB increase (can be more more on the pages with active campaigns). It is not as bad as the Drift, but is still a lot.

I understand that we can't remove GTM and all counters from the site, but it can be a good idea to reevaluate them and only left the ones that are truly necessary.

Also GTM bundles all user's account settings, triggers, code blocks and other code inside the bundle that it is creating for the site. So it can be a good idea to removed unused variables and code blocks from it and only add them back then the company is active. Right now GTM by itself adds 101 KiB to bundle size, which is quite a lot.

### Full: Baseline + GTM + GTAG + Drift 

Performance score: 48,4 (51, 52, 44, 47, 48)

| Resource Type | Requests | Transfer Size |
| --------------- | --------: | ------------: |
| Total                  |          175 |    1,705.9 KiB |
| Script                |            91 |       976.7 KiB |
| Image                |           30 |      456.5 KiB |
| Font                   |             6 |      138.6 KiB |
| Stylesheet         |           14 |        45.9 KiB |
| Other                 |           30 |        44.6 KiB |
| Document         |              4 |        43.7 KiB |
| Media                |              0 |          0.0 KiB |
Third-party         | 117           |      873.3 KiB |

Just to reiterate, right now we load 91 requests and 976.7 KiB of JavaScript code and only 1/3 of it is our code. We should reduce it somehow to make pages load faster and Ligthouse score better.

## ToDo

- [ ] Defer initialization of reCaptcha until form elements are clicked.
- [ ] Hide Drift inside the https://github.com/calibreapp/react-live-chat-loader to defer it's initialization.
- [ ] Reevaluate counters list inside GTM.
- [ ] Remove no longer needed settings, triggers and code blocks from GTM.

**Comment by C-STYR** [comment]
Certainly agree on points 1 & 2.  Also, this format is fine by me but Alex will have to make that call.
