### ISSUE TITLE
Blog Phase 1

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#886]
### Goal
Create a separate repo for the blog that is functional using markdown. This repo should be clean of any previous dependancies that are not needed from the next/ repo 

### Tasks
- [ ] Create Separate Branch
- [ ] Remove unneeded plugins or dependancies 
- [ ] Remove unneeded components 
- [ ] Get blog posts synced with latest
- [ ] Create a Vercel instance for the blog
- [ ] Get code review from @alexwolfe
- [ ] Run SEMRush check on staged instance to check for SEO issues 

### DO NOT ADD TO BRANCH
- Contentful
